
name: 'music_growth'
version: '1.0.0'
profile: 'music_growth'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  music_growth:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
      +grants:
        select: ['app_readonly']
    api:
      +materialized: table
      +grants:
        select: ['app_readonly']

on-run-start: "set lock_timeout = '5s'"